movies/config/routes.rb
Rails.application.routes.draw do
  resources :actors

    get "home/index"
	get "admin/login"
	get "admin/logout"
	post "admin/login"

end

movies/app/models/actor.rb
class Actor < ActiveRecord::Base
     self.per_page = 3
     validates :name, uniqueness:	 true
     validates :name, presence: true
	 validates :age, numericality: true
	 #validates :moviesno, numericality: true
	 validates :name,length: { minimum: 3 }

	 before_save :merge_actor_name
	 after_destroy :display_message
	 
	 def merge_actor_name
	 
	     self.name = self.name + " by " + self.age.to_s
	 
	 end
     
	 def display_message
	 
	    logger.error "A field has been deleted......"
		
	 end
	 
end

movies/app/models/film.rb
class Film < ActiveRecord::Base
end

movies/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  before_filter :admin_loggedin?
  
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.paginate(:page => params[:page])
	
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
	     PostMan.admin_alert(@actor).deliver
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :age, :noofmovies)
    end
	
	def admin_loggedin?
	    if session[:admin].nil?
		   flash[:notice]="please login to continue"
		   redirect_to :controller=>"admin",:action=>"login"
	    end
	end
end

movies/app/controllers/admin_controller.rb
class AdminController < ApplicationController
   def login
	if request.post?
	    if params[:admin][:name] == "admin" && params[:admin][:password]=="12345"
	       session[:admin]="admin"
		   flash[:notice]="Login Succesful"
		   redirect_to :controller=>"actors"
		else
		   flash[:notice]="Username or Password Doesn't match. Try Again"
		   render :action=>"login"
		end
		   
    end
   end


def logout
    session[:admin]=nil
	flash[:notice]="you are logged out"
	render :action=>"login"
end

end

movies/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

movies/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

movies/app/helpers/actors_helper.rb
module ActorsHelper
end

movies/app/helpers/admin_helper.rb
module AdminHelper
end

movies/app/helpers/application_helper.rb
module ApplicationHelper
end

movies/app/helpers/home_helper.rb
module HomeHelper
end

movies/app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :moviesno %><br>
    <%= f.text_field :moviesno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movies/app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

movies/app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Noofmovies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.age %></td>
        <td><%= actor.moviesno %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>


<%= will_paginate @actors %>

movies/app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

movies/app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @actor.age %>
</p>

<p>
  <strong>Noofmovies:</strong>
  <%= @actor.moviesno %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

movies/app/views/admin/login.html.erb
<%= form_for(:admin) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit "login"%>
  </div>
<% end %>

movies/app/views/home/index.html.erb
<h2>welcome to my first rails page #saiseshu</h2>


<%= form_tag("/search", method: "get") do %>
<%= label_tag(:q, "search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

movies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main-out">
<div class="main">
<div class="page">
<div class="top">
<div class="header">
<div class="header-top">
<h1>My <span>FirstApp</span></h1>
<p>Call Us: 000 0000 000</p>
</div>
<div class="topmenu">
<ul>
  <li><a href="index.html">Home</a></li>
  <li><a href="#">About&nbsp;Us</a></li>
  <li><a href="#">What's&nbsp;New</a></li>
  <li><a href="#">Services</a></li>
  
 <% if session[:admin] %>
  <li>Admin logged in...</li>
  <li><a href="/admin/logout">Logout</a></li>
 <% else %>
  <li><a href="/admin/login">Login</a></li>
 <% end %>
  <li><a href="#">Resources</a></li>
  

</ul>
</div>
<div class="header-img">
<h2>Saiseshu Kodali</h2>
</div>
</div>
<div class="content">
<div class="content-left">
<div class="row1">
<div class="img"><img src="/assets/img1.jpg" alt="" height="101"
 width="157"></div>
<div class="welcome">
<h1 class="title">Welcome to <span>My First App</span></h1>

<%= yield %>

</div>
</div>
<div class="row2">
<div class="section1">
<h2 class="subtitle">What&#8217;s New</h2>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p><a href="#" class="more">read more</a></p>
</div>
<div class="section2">
<h2 class="subtitle">Resources</h2>

<p>&nbsp;</p>
<p><a href="#" class="more">read more</a></p>
</div>
</div>
</div>
<div class="content-right">
<h2>Main Menu</h2>
<ul>
  <li style="border-top: medium none;"><a href="#">Link 1</a></li>
  <li><a href="#">Link 2</a></li>
  <li><a href="#">Link 3</a></li>
  <li><a href="#">Link 4</a></li>
  <li><a href="#">Link 5</a></li>
  <li><a href="#">Link 6</a></li>
  <li><a href="#">Link 7</a></li>
  <li><a href="#">Link 8</a></li>
  <li><a href="#">Link 9</a></li>
  <li><a href="#">Link 10</a></li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>
</div>
</div>
<div class="bottom">
<ul>
  <li style="border-left: medium none;"><a href="index.html">Home</a></li>
  <li><a href="#">About&nbsp;Us</a></li>
  <li><a href="#">What's&nbsp;New</a></li>
  <li><a href="#">Services</a></li>
  <li><a href="#">Contact</a></li>
  <li><a href="#">Resources</a></li>
  <li><a href="#">Links</a></li>
</ul>

<!--DO NOT Remove The Footer Links-->
<p>&copy; Copyright 2014. Designed by <a target="_blank" href="http://www.usaonlinecasinos.org">usaonlinecasinos.org</a></p>
<!--Designed by--><a target="_blank" href="http://www.usaonlinecasinos.org">
<img src="/assets/footnote.gif" class="copyright" alt="http://www.usaonlinecasinos.org"></a></div>
<!--DO NOT Remove The Footer Links-->
</div>
</div>
</div>

</body>
</html>

movies/app/views/post_man/admin_alert.html.erb
HI admin,<br/>

A new record has been added to Database.<br/>

Here are details<br/>

id <%= @id%><br/>
Name <%= @name%><br/>



Thanks,
post_man